apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole