---
- name: Prepare all nodes
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Configure /etc/hosts for cluster nodes
      blockinfile:
        path: /etc/hosts
        block: |
          # Kubernetes cluster nodes
          {% for host in groups['masters'] | default([]) %}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}
          {% endfor %}
          {% for host in groups['workers'] | default([]) %}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED KUBERNETES CLUSTER HOSTS"
        create: yes
        backup: yes